services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    ports:
      - "8001:8001"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data: